baseURL = "/ycas/"
languageCode = "en-us"
theme = "casper-two"
publishDir = "../"
paginate = 6

[params]
    title = "York County Astronomical Society"

    author = "EM"
    authorAvatar = "img/ghost-icon.png"
    authorLocation = "York, PA"
    authorWebsite = "https://eueung.github.io"
    authorDescription = "Formed in 1989, the non-profit York County Astronomical Society aims to promote interest, public education, and advancement of the science of astronomy. In addition to planetarium shows, the society presents regular public sky watches and astronomy classes."

    cover = "img/Observatory.jpg"

    fbName = "astroyork"

    pageNotFoundTitle = "404 - Page not found"

    #casper or caspertwo
    singleViewStyle = "casper"

    [permalinks]
        post = "/post/:slug/"

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 200