baseURL = "/ycas/"
languageCode = "en-us"
theme = "casper-two"
publishDir = "../"

[params]
    title = "York County Astronomer's Society"
    subtitle = "Welcome to the new YCAS Website!"

    cover = "Space.png"

    twitterName = "faketryghost"
    fbName = "fakeghost"

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 200

    [[menu.main]]
        name = "Events"
        url = "/events"
        weight = 100